# Thank you to Matéu.sh for his article and GitHub repository about GitHub Workflows.
# Article: https://www.freecodecamp.org/news/how-to-deploy-next-js-app-to-github-pages/
# GitHub Repository: https://github.com/mateuszsokola/2048-in-react.git
# Changed names and version numbers from original repository.
name: predeploy
description: "Sets up Node.js, installs and caches dependencies"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4.2.0
      with:
        node-version: '22'
        #node-version-file: ".nvmrc"

    - name: Cache frontend dependencies
      id: cache_frontend
      uses: actions/cache@v3.4.3
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: frontend/node_modules
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-frontend-

    - name: Install frontend dependencies
      shell: bash
      run: npm ci --prefix frontend

    - name: Cache backend dependencies
      id: cache_backend
      uses: actions/cache@v3.4.3
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: backend/node_modules
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-backend-

    - name: Install backend dependencies
      shell: bash
      run: npm ci --prefix backend
