# Thank you to Matéu.sh for his article and GitHub repository about GitHub Workflows.
# Article: https://www.freecodecamp.org/news/how-to-deploy-next-js-app-to-github-pages/
# GitHub Repository: https://github.com/mateuszsokola/2048-in-react.git
# Modified code provided by Duck.ai's ChatGPT4o-mini

#Prompt: User. (2025). I want to deploy a full stack web application to GitHub pages via GitHub actions... [Prompt to AI language model].
#Response: OpenAI. (2025). To deploy a full-stack web application to GitHub Pages using GitHub Actions... [Response from AI language model].

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '22'  # Specify the Node.js version you want to use

      - name: Cache Node.js modules
        uses: actions/cache@v3.4.3
        with:
          path: |
            frontend/node_modules
            backend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5.0.0
        with:
          static_site_generator: next

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./frontend/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
